apiVersion: v2
name: plausible-analytics
description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly alternative to Google Analytics
type: application
home: https://plausible.io/
icon: https://docs.plausible.io/img/logo.svg
keywords:
  - plausible analytics
  - analytics
sources:
  - https://0xacab.org/varac-projects/plausible-helm-chart
  - https://hub.docker.com/r/plausible/analytics
  - https://github.com/plausible/analytics
maintainers:
  - name: Varac
    url: https://varac.net
  - name: Vadim Bauer
    url: https://8gears.com
version: 0.4.26
appVersion: v1.5.1
dependencies:
  # https://artifacthub.io/packages/helm/sentry/clickhouse
  - name: clickhouse
    version: 3.3.0
    repository: https://sentry-kubernetes.github.io/charts
    condition: clickhouse.enabled
  # https://artifacthub.io/packages/helm/bitnami/postgresql
  - name: postgresql
    version: 12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
# https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations
annotations:
  # artifacthub.io/containsSecurityUpdates: "true"
  # artifacthub.io/images: |
  #   - name:
  #     image: repo/img1:1.0.0
  artifacthub.io/license: Apache-2.0
  # artifacthub.io/signKey: |
  #   fingerprint: C874...
  #   url: https://keybase.io/hashicorp/pgp_keys.asc

  # https://blog.artifacthub.io/blog/changelogs/
  # valid supported kinds are added, changed, deprecated, removed, fixed and security
  artifacthub.io/changes: |
    - kind: changed
      description: added option to override value for SECRET_KEY_BASE
